### ISSUE TITLE
future compatibility problem in dependencies

### ISSUE THREAD

**Issue by hdhoang** [maralorn/tasktree#3]
Hi, due to rust-lang/rust#49799, one of your dependencies will no longer build. From looking at your
Cargo.toml, we recommend you upgrade to
a newer gtk-rs (0.4 or later). Thanks for your attention!

**Comment by maralorn** [comment]
Thank you very much for the hint! I will get to it as soon as I can.

**Comment by maralorn** [comment]
Fixed by #4
